server:
  port: ${PORT:8080}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Players: acepta /api/players/** (passthrough)
        - id: players-service-api
          uri: ${PLAYERS_URI:http://localhost:8081}
          predicates:
            - Path=/api/players/**
        # Players: acepta /players/** y reescribe a /api/players/**
        - id: players-service-noapi
          uri: ${PLAYERS_URI:http://localhost:8081}
          predicates:
            - Path=/players/**
          filters:
            - RewritePath=/players/(?<segment>.*), /api/players/${segment}
        # Teams: acepta /api/teams/** (passthrough)
        - id: teams-service-api
          uri: ${TEAMS_URI:http://localhost:8082}
          predicates:
            - Path=/api/teams/**
        # Teams: acepta /teams/** y reescribe a /api/teams/**
        - id: teams-service-noapi
          uri: ${TEAMS_URI:http://localhost:8082}
          predicates:
            - Path=/teams/**
          filters:
            - RewritePath=/teams/(?<segment>.*), /api/teams/${segment}
      default-filters: []
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
